project:
  type: website
  output-dir: docs
website:
  title: "MyDataRules (MyDR)"
  reader-mode: false
  favicon: favicon-16x16.png
  google-analytics: "G-MB64NTVJTB"
  open-graph:
    site-name: MyDataRules
  navbar:
    background: "#f3f4f5"
    right:
      - index.qmd
      - text: "Me"
        file: index_b.qmd
      - research.qmd
      - text: "Meetup"
        href: https://www.meetup.com/r-business/
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/m45hap
  page-footer:
    left: "Copyright 2023, Maria Prokofieva"
    right:
      - text: "Meetup"
        href: https://www.meetup.com/r-business/
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/m45hap
    background: "#f3f4f5"
format:
  html:
    theme: litera



